### ISSUE TITLE
Unable to get mention array from listener

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#101]
Hi szweier,

I have recently updated my project SZMentionsSwift library from version 2.0.5 to 2.0.7 and I realised that the public method for getting mention array is unavailable to access anymore. May I know if there any public method for me to access it?

**Comment by szweier** [comment]
@wonderhero please use version 2.0.8 that I just pushed, it should have the fix you need.

**Comment by wonderhero** [comment]
@szweier thank you.
