### ISSUE TITLE
String index is out of bounds error when mentioned text contain Emoji

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#113]
Hi szweier,

If I have enabled spaceAfterMention and searchSpaces and my mentioned text contains Emoji character eg:  😌The library will crash at line 262 of MentionListener class file. 

`let endIndex = mentionsTextView.text.index(startIndex, offsetBy: NSMaxRange(textView.selectedRange) - location)`

`Fatal error: String index is out of bounds`

Could you please assist? Thank you.

**Comment by szweier** [comment]
@wonderhero sorry for the delay, can you try https://github.com/szweier/SZMentionsSwift/pull/114 I believe it should resolve your issue.

**Comment by wonderhero** [comment]
@szweier it is working like a charm now. Thank you for your solution.
