### ISSUE TITLE
String index is out of bounds when mentioned text contain Emoji and newline character "\n"

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#116]
Hi szweier,

I have another error related to emoji character (UTF16)

Input = `@mentionwithemoji😌\n @` _<- trigger mention again after newline will cause String index is out of bounds error at String extension class._

Error at line 32 of **isMentionEnabledAt()** function. 
`let start = index(startIndex, offsetBy: location - 1)`

Could you please kindly assist on the issue? Thank you.

**Comment by patrickd105** [comment]
Hey @wonderhero , could you check if the changes I put up for PR here https://github.com/szweier/SZMentionsSwift/pull/117 fix your issue? If so we can link this issue to that PR

**Comment by wonderhero** [comment]
Hi @patrickd105, I have checked your PR. It is working fine and fixed my issue. Thanks.

**Comment by szweier** [comment]
I'm closing this issue asI've merged #117
