### ISSUE TITLE
UITextView autoCapitalizationType is always Words

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#119]
Hi szweier,

The mentions library has overwritten my UITextView autoCapitalizationType type. It always capitalizes Words even though I have set my UITextView to Sentences. [For the auto-suggestion words] 

I have tested with the sample in this project. 

![Screenshot 2019-10-24 at 4 22 49 PM](https://user-images.githubusercontent.com/3401072/67467631-ac155400-f67b-11e9-87bd-81d067f29f34.png)

Could you please assist?

Thank you.

**Comment by szweier** [comment]
Looks like something specific to iOS 13, I'm looking now.

**Comment by wonderhero** [comment]
Hi szweier,

It is working perfectly. Thank you for helping.

**Comment by szweier** [comment]
Thanks for confirming.
