### ISSUE TITLE
How to get an array text from String?

### ISSUE THREAD

**Issue by Terens777** [szweier/SZMentionsSwift#124]
i have string 

"Hello my name Andre Tan i love Olga Kiseleva"

and have - Array  with [Mention] -> Andre Tan, Olga Kiseleva

how get ?
`
["Hello my name ", "Andre Tan", " i love ", "Olga Kiseleva"]
`
Is there any way to solve this?
thanks

**Comment by szweier** [comment]
There’s nothing specifically provided by this library to return that type of array. You could however generate that array by using the mention ranges to create that array. I’m thinking something like getting the range of string from 0 to the first mention’s location. Then you can get the first mention using its location and length and continue that type of pattern until you parse the entire string

**Comment by Terens777** [comment]
Thanks
