### ISSUE TITLE
Auto Correct suggestion issue

### ISSUE THREAD

**Issue by Indolia** [szweier/SZMentionsSwift#125]
Keyboard show some incorrect suggestions after set the attributed string in textview. 
In should change delegate. Its come only in iOS 13. In iOS 12 it is working fine. Please look into this.
![597233243 425042](https://user-images.githubusercontent.com/13569479/70498270-dc398900-1b3b-11ea-88d7-606608d164d6.png)

**Comment by szweier** [comment]
@Indolia 
Which version of iOS 13 were you seeing this issue on (I tested on 13.3 and was seeing decent suggestions)?
The suggestions don't look that bad to me, what were you expecting to see?

**Comment by szweier** [comment]
I'm going to close this issue, if there's more information you can provide please feel free to reopen.
