### ISSUE TITLE
Remove a mention in one stroke not working  when using backspace button on keyboard

### ISSUE THREAD

**Issue by kirti301290** [szweier/SZMentionsSwift#126]
Hello
backspace delete mention not working here i trying to explain  criteria
i mentioned Text like hi @User1 @User2 and @User3 and i tried to delete **User1** using backspace it working then try to delete **User2** then it works but when i try to delete  **User3** then it not working  also some time app crashing
Pls give me solution how it work 
Thanks in advance

**Comment by szweier** [comment]
@kirti301290 I believe https://github.com/szweier/SZMentionsSwift/pull/127 will fix your issue, please give that a try. I'll get it into the next release.
