### ISSUE TITLE
Deleting all the text causes a crash

### ISSUE THREAD

**Issue by jrodriguezbebee** [szweier/SZMentionsSwift#21]
When you have more than one mention and try to select all the text and delete it causes a crash. The problem occurs in shouldAdjust, specifically in forceDefaultAttributes when trying to do this:

`mutableAttributedString.mutableString.replaceCharacters(in: range, with: text)`

In handleEditingMention you are handling only one mention(the last you find) and deleting all the text from de textView but the range that you pass to forceDefaultAttributes is still the older one, so you get an out of bounds when you try to replace text in an empty string.

**Comment by szweier** [comment]
Hi, thanks for reporting the issue.  I just tried typing a comment with two mentions in it, selecting the entire body of text and hitting delete.  I didn't come across a crash in doing so. Are there more specific repro steps you can provide? My test for example was the following:

1. Type mention string : "Testing that mentions work @mention1 when mentioning two @mention2 people."
2. Select all
3. Delete
4. Type new string: "Test"

But I didn't come across a crash.

**Comment by jrodriguezbebee** [comment]
Hi,

You can try with this simple texts:

@Steven Zweier @John Smith **-> Select all and delete it**
@Steven Zweier @John Smith **-> Select @John Smith and partially @Seteven Zweier**

I hope this can be helpful.
Best regards.

**Comment by szweier** [comment]
Thank you for this info, I apologize for the delay but I believe I have a fix and will get a new release out shortly.

**Comment by szweier** [comment]
@jrodriguezbebee sorry for the long delay in fixing this issue.  I've added code located here: https://github.com/szweier/SZMentionsSwift/pull/23 please test it and let me know if you believe this fixed the issue.

**Comment by szweier** [comment]
Closing this issue now that #23 has been merged.
