### ISSUE TITLE
Should insertExistingMentions be made public?

### ISSUE THREAD

**Issue by raphaelcruzeiro** [szweier/SZMentionsSwift#32]
I'm trying to initialise the `SZMentionsListener` with a preexisting list of mentions. I found the `insertExistingMentions` method which seems to do what I want but the method is inaccessible from outside of the framework. Is this by design or should this method be made public?

**Comment by szweier** [comment]
@raphaelcruzeiro you are absolutely correct this should be made public.  I just opened a PR to fix this.  Thanks for reporting the issue.

**Comment by raphaelcruzeiro** [comment]
Somewhat related to this: After initialising the textView with a text and inserting the existing mentions on the `SZMentionsListener`, the mention attributes are not applied (though it seems at the mention is correctly added to the mention list of the listener). Am I missing some step here?

**Comment by szweier** [comment]
@raphaelcruzeiro sorry for the delay, it should be working.  I've added it to the PR mentioned above as part of the example app.  Please let me know if that example helps.

**Comment by szweier** [comment]
@raphaelcruzeiro version 1.0.2 should have what you're looking for.
