### ISSUE TITLE
Is it possible to continue searching possible mentions with a space in the filter string?

### ISSUE THREAD

**Issue by camdengaba** [szweier/SZMentionsSwift#42]
I'd like to be able to search my app's users by their full name, but currently, typing a space ends the search process.  Is this possible to allow spaces in the filter string?

Sorry if the question is unclear, and great work; this project has been a lifesaver.

**Comment by szweier** [comment]
At the moment this is not possible, though I don't mind it as an enhancement to this project.  Will take a look into making this possible.

Glad to hear it's working well for you otherwise.

**Comment by szweier** [comment]
@camdengaba I've opened a PR with this functionality.  There are some more things I'd like to look into before releasing this feature but if you'd like to try it out you can find it here:
https://github.com/szweier/SZMentionsSwift/pull/43

**Comment by camdengaba** [comment]
Wow, I was not expecting such a quick response.  Thank you!
