### ISSUE TITLE
Trigger symbol

### ISSUE THREAD

**Issue by ndemenko** [szweier/SZMentionsSwift#50]
Can I keep printing trigger symbol inside text view? And how? (Like on git @name)

**Comment by szweier** [comment]
Hi I believe the answer you're looking for is at the bottom (third from the last comment) on this issue. https://github.com/szweier/SZMentionsSwift/issues/20

**Comment by szweier** [comment]
@ndemenko did you find what you were looking for in that other issue, is there anything more I can do to help you here?

**Comment by ndemenko** [comment]
no. thanks for help. problem was resolved.
