### ISSUE TITLE
Multiple triggers

### ISSUE THREAD

**Issue by lucas34** [szweier/SZMentionsSwift#55]
Hi,

Currently the trigger is limited to 1 String. Is it possible to have a collection of Strings as trigger. I would like to have '@' but also '＠' (Japanese @). 

What do you think ?

**Comment by szweier** [comment]
Very interesting, I'll look into it.

**Comment by szweier** [comment]
@lucas34 I've opened up a PR here: https://github.com/szweier/SZMentionsSwift/pull/56 it should be working if you'd like to test it out. I'm going to be working on adding some tests and a little bit of code cleanup before merging but you can use it from this branch for now.

**Comment by szweier** [comment]
Also, while I don't mind allowing for multiple triggers as it may be useful to someone I believe that in your example above you might be better off localizing the string you pass in for the trigger. That way the proper trigger would be used based on the device.
