### ISSUE TITLE
Exception 'NSRangeException' for searchSpaces feature

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#59]
First of all, thank you for the great library that you have written. I have discovered an issue that could be reproduce as following:

1. Enable **searchSpaces** in SZMentionsListener
2. Type **Any String "@tag String" Any String** in text view.
3. Randomly **keep changing cursor (Select text position) position** (In quick manner) in text view.

It will throw the Range out of bounds issue.

Example of error message: 
`*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {72, 18} out of bounds; string length 86'`

**Comment by szweier** [comment]
Apologies for the delay here. I will look into this. Thank you for the bug report.

**Comment by szweier** [comment]
@wonderhero I'm a bit confused by the steps here. For step 2 am I typing `Any String` then creating a tag and then typing `Any String`? So the end result would be `Any String` on either side of a mention?

**Comment by wonderhero** [comment]
@szweier Thank you for your response. Sorry for the unclear explanation, `Any String` is mean to type any characters before and after a mention. 

Example: **This is a test to** `@mention` **someone**.

**Comment by szweier** [comment]
Thanks, and then just moving the cursor will trigger this issue?

**Comment by wonderhero** [comment]
@szweier Yea. Thank you.

**Comment by szweier** [comment]
@wonderhero are you able to reproduce this in the example app? Pull this repo and run the SZMentionsExample scheme. I can't seem to reproduce this problem.

**Comment by wonderhero** [comment]
@szweier I will try first and update you later. Thanks again.

**Comment by wonderhero** [comment]
@szweier I have ran the SZMentionsExample scheme. I couldn't reproduce the problem. You may proceed to close this issue. I will look into my implementation that cause the issue. Thank you again for your effort in making this great library.

**Comment by szweier** [comment]
No problem. Good luck tracking down the issue. If it turns out to be in this library please feel free to open another ticket.
