### ISSUE TITLE
Option to not replace the trigger

### ISSUE THREAD

**Issue by elanovasconcelos** [szweier/SZMentionsSwift#60]
Hello,

Is it possible to avoid the trigger replacement? So the final result is "@name" not "name".

I tried to change a little SZMentionsListener, but it just created bugs.

thanks!

**Comment by szweier** [comment]
I noticed you closed this shortly after opening the ticket. Just in case you were still curious about the answer (and for those who may end up at this issue when trying to solve a similar problem). The best answer is located here: https://github.com/szweier/SZMentionsSwift/issues/20#issuecomment-259135782
