### ISSUE TITLE
textView(_:shouldChangeTextIn:replacementString:) not been called

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#65]
Hi szweier,

I have added SZMentionsListener in my code. I also implemented textView(_:shouldChangeTextIn:replacementString:) in my controller. I realised that if I paste string from external app into the textview that has implemented this library. My callback not getting called. I have stepped into the library code.

```
else if text.count > 1 {
            //Pasting
            if let editedMention = mentions.mentionBeingEdited(atRange: range) {
                clearMention(editedMention)
            }

            textView.delegate = nil
            if let mutableAttributedString = textView.attributedText.mutableCopy() as? NSMutableAttributedString {
                mutableAttributedString.replaceCharacters(in: range, with: NSAttributedString(string: text))
                mutableAttributedString.apply(defaultTextAttributes, range: NSRange(location: range.location, length: text.count))
                mentionsTextView.selectedRange = NSRange(location: 0, length: 0)
                textView.attributedText = mutableAttributedString
                mentionsTextView.selectedRange = NSRange(location: range.location + text.count, length: 0)
            }
            
            mentions.adjustMentions(forTextChangeAtRange: range, text: text)
            textView.delegate = self
            
            return false
        }
        _ = delegate?.textView?(textView, shouldChangeTextIn: range, replacementText: text)
```
The delegate callback will not get called if it fulfilling the text pasting action. However, I need to do some adjustment to my UITextView (To resize the UI) if received the callback. 

Is there any way I can get my delegate get called in the event of pasting text?

**Comment by szweier** [comment]
@wonderhero please check out this PR and let me know if it solves your problem. https://github.com/szweier/SZMentionsSwift/pull/66

**Comment by wonderhero** [comment]
@szweier I have tested the code and tried to step into the implementation. The defer statement still not getting called. Would you mind to have a check on this again?

**Comment by szweier** [comment]
@wonderhero are other delegate methods being called? I find it strange that the defer wouldn’t be hit. Any chance you can push a sample app to a public repo that demonstrates this problem?

**Comment by wonderhero** [comment]
@szweier yes, other delegate methods working well. Only textView(_:shouldChangeTextIn:replacementString:) not been called. Let me try setup a sample app for this.

**Comment by szweier** [comment]
@wonderhero I just placed the following code into the `ExampleViewController`

```
    func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        print("called")
        return true
    }
```

And it appears to be getting called (print statement is shown in console). It is worth noting that, due to the way the listener works, what you return from this method is ignored.

**Comment by wonderhero** [comment]
@szweier I have setup a sample project to test this. Would you mind to check it out? https://github.com/wonderhero/SampleMentionApp 

If I paste a text into the textview. The print text won't get executed.

```
func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange,
                  replacementText text: String) -> Bool {
        print("TextView change text in")
        return true
    }
```

**Comment by wonderhero** [comment]
@szweier You are right, I have tested it. The listener is working. It is my bad.

**Comment by DavonMars** [comment]
In my case I forgot to initialize listener with viewController delegate 
`public init(
        mentionsTextView: UITextView,
        **delegate: UITextViewDelegate? = nil,**
        ...`
