### ISSUE TITLE
Exception 'NSRangeException' for searchSpaces feature

### ISSUE THREAD

**Issue by wonderhero** [szweier/SZMentionsSwift#69]
@szweier I able to reproduce this issue again. It is just a bit tricky.

Step to reproduce:
1. Enable `searchSpaces` in `SZMentionsListener`
2. Type `Hello this is example of @mention @this_is_false_mention` in text view.
3. Randomly keep changing cursor (Select text position) position (In quick manner) in text view.

**@mention** is actual mention
**@this_is_false_mention** is a random string that having starting character same as `triggers`. Example: "@" symbol.

I able to reproduce the issue in the project example as well. 

It will throw the Range out of bounds issue.

Example of error message:
`*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {72, 18} out of bounds; string length 86'`

**Comment by wonderhero** [comment]
As long as there is `triggers` character in the string, it will throw the range out of bounds runtime error.

**Comment by wonderhero** [comment]
Affect this closed issue as well. [#20](https://github.com/szweier/SZMentionsSwift/issues/20) To show trigger character. If the trigger character is presented in the string. It will cause this runtime error as well when the cursor moving around in the string.

**Comment by szweier** [comment]
I'm still unable to reproduce this. Are you reproducing this on a simulator or device? I'll keep trying, but so far, no luck. Any chance you can write a unit test that results in this crash?

**Comment by szweier** [comment]
My mistake, I was setting the wrong bool to `true`. I reread your issue and believe I understand what's going on. Hopefully I can figure out a solution tonight.

**Comment by szweier** [comment]
@wonderhero thanks for pressing the issue here. I found it and will be pushing a new version shortly.

**Comment by wonderhero** [comment]
@szweier Thanks for resolving the issue. Will buy you a coffee.
