### ISSUE TITLE
Swift 4 not supported?

### ISSUE THREAD

**Issue by kuntal33** [szweier/SZMentionsSwift#71]
When I run pod install it installs SZMentionsSwift (1.0.9) and this version is giving me compile time error for attributed key names. 
Please help me

**Comment by szweier** [comment]
Is your podfile specifying that version? Seems like maybe you also want to run `pod update` rather than install, your podfile.lock may well be pointing to 1.0.9 and keeping you there when running `pod install`.

**Comment by szweier** [comment]
@kuntal33 I believe my comment above will fix your issue. I'm going to close this issue, if you're still having trouble please reopen the issue and I will continue to try to assist you. Keep in mind, you may get a warning when trying `pod update` telling you to run `pod repo update`. That combination should fix the problem you are seeing.
