### ISSUE TITLE
If there is a emoji before a mention and I try to insert existing mention, Assertion Test fails

### ISSUE THREAD

**Issue by asim1mehta** [szweier/SZMentionsSwift#73]
Input String -> "🦅 Asim"

range.location = 3
range.length = 4
mutableAttributedString.string.count = 6

**Comment by asim1mehta** [comment]
For now I changed  **mutableAttributedString.string.count** to **mutableAttributedString.string.utf16.count**
```
 assert(range.location + range.length < mutableAttributedString.string.utf16.count,
                       "Mention range is out of bounds for the text length")
```

**Comment by szweier** [comment]
This looks like the perfect solution for this problem. Would you be willing to open a PR for this and add a test that demonstrates the problem.

**Comment by szweier** [comment]
@asim1mehta please try version 2.0.3 as it should contain the fix you're looking for for this issue.

**Comment by asim1mehta** [comment]
Thanks @szweier 🙂
