### ISSUE TITLE
Can you make "resetEmpty" public?

### ISSUE THREAD

**Issue by asim1mehta** [szweier/SZMentionsSwift#75]

**Comment by szweier** [comment]
Aside from potential bugs in the library I don't see the need to make `resetEmpty` public. I am opened to having a discussion about this, I can be convinced.

**Comment by asim1mehta** [comment]
I need to clear the textView and mentions without user's action.

How else can I achieve it?

**Comment by asim1mehta** [comment]
If I set the text to "",  mentions will not be cleared and when I will access the mentions old mentions will still be there.

**Comment by szweier** [comment]
Sorry I haven’t gotten to check into this yet. Can you try calling textView.insertText(“”) that should trigger all events and wipe out mentions.
