### ISSUE TITLE
When Capitalization for sentences is enabled, After entering first digit Capitalization is not disabled when using GBoard.

### ISSUE THREAD

**Issue by asim1mehta** [szweier/SZMentionsSwift#79]
It happens only when using GBoard.

I guess it is happening because the text field is being reset.

It does not happen if we do not reset the text field when replacementText.count == 1, both in `shouldAdjust(_ textView: UITextView, range: NSRange, text: String)` and `
textView(_ textView: UITextView, shouldChangeTextIn range: NSRange,
                        replacementText text: String) -> Bool
`

**Comment by szweier** [comment]
@asim1mehta I apologize for the delay. I've just tried out Gboard and I don't see the problem. Have my recent changes to the library resolved this issue for you? The testing I did was to run the example library on my device with the Gboard enabled, I then deleted all of the text from the textView and started typing a sentence. Only the first letter was capitalized. Assuming I tested this properly I believe this is fixed but I wanted to confirm with you to see if there's something additional I should be testing.
