### ISSUE TITLE
Different styles for different kind of mentions

### ISSUE THREAD

**Issue by Footjy** [szweier/SZMentionsSwift#80]
Hey, 

Thanks for the lib! In my case I need to manage 2 different kinds of mentions: some mentions should appear in blue, some others should appear in gray. But currently it seems you can only have them all blue, or all gray.

Do you think we could add this feature to the lib? I could help if needed.

**Comment by szweier** [comment]
That's a very interesting idea, I'll find some time to look into it. What would be the necessary information for you to decide on the color you'd want to see? For example, if you were given the mention name could you determine the color?

**Comment by szweier** [comment]
This is definitely something I need to give some more thought to before building. My initial intention was to guide the user of this library by making sure they used the same attributes for both the mention and the regular text. The reason for this was to avoid strange text effects. For example if you had the font set for mentions but not regular text, then you'd have the default text for the first bit of text you typed, then you add a mention and it changes the font. When you go back to regular text the font would remain the mention font you chose while the colors and whatever else would go back to regular text. 

The way I'd think about implementing your request would be to change both the mentions and default text arrays to closures that you would return the attributes you want. While that SHOULD work (untested theory thus far) it would mean that the validation of the users choices would need to be removed. 

Removal of that validation is not the end of the world, allowing users of the library to make their own decisions (even if I consider them wrong) should be possible...maybe...

In any case, not sure if all those thoughts above are of interest to you but that is where I am at the moment with regard to this feature request.

**Comment by Footjy** [comment]
Thank you for your quick answer. Your thoughts are very interesting.

To decide on the color of the mention I would need more than the name. I would need some parameter stored in the `CreateMention` object. Something like a "disabled" Bool. So your idea of a closure seems like a good way to go, having the `Mention`, or `CreateMention` object in parameter.

I can think of a way to do that keeping the validation: the closure could take the `CreateMention/Mention` object as parameter, and return a dictionary of attributes. You would then copy the already validated `mentionTextAttributes` dictionary, and modify the values of the attributes returned by the closure. That way you make sure that the attributes we want to change for a mention are expected, without doing the full validation every time you add a mention.

What do you think?

**Comment by szweier** [comment]
Interesting thoughts but I think it may be overkill to simply try to guide users of the lib down a specific path. I opened a PR with changes I think will work just fine but would like you to give it a try and let me know your thoughts. Validation would now only work on the first request (so in theory a dev could write code that passes in the default case and fails to change all necessary styles for another case).

**Comment by Footjy** [comment]
Great, thank you very much, it looks like what I need! I did not find the time to test it today unfortunately, I think it will have to wait until next Tuesday, sorry for that. I'll let you know then if it works.

**Comment by Footjy** [comment]
Hey thank you very much, I tried it and it works perfectly. Sorry about the delay.

**Comment by Footjy** [comment]
As a corollary, do you think it might be possible to make the mutable mention array accessible somehow? 

Here is my business case, so you can understand it better: I can post some message in a group and mention some users. But while editing the message I can change the group in which to post, thus making some users unavailable. So I need to change the style of the mentions of those users to gray. I can also change the group back to the previous one, so the grayed mention is available again and I need to switch it back to blue. I hope it's clear why I'm asking this.

Again this would mean leaving more control to the user and opportunities for errors. I can off course submit a PR if it helps you.

**Comment by szweier** [comment]
Sorry for the delayed response here. Yea I think it'd be best to open an additional issue for this. I'm going to work on getting the PR for the original fix merged and deployed soon (not sure about tonight just yet).
