### ISSUE TITLE
HideMentions() not called when pasting text.

### ISSUE THREAD

**Issue by Footjy** [szweier/SZMentionsSwift#84]
Hey thank you for the lib,

When you type in `@` the showMentionsList() method is called, so the list of possible mentions is displayed. But when pasting (or adding an emoji) there is no call to hideMentions() so the list remains.

I suggest calling `hideMentions()` in `func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String)`.

Thanks,

**Comment by Footjy** [comment]
@szweier Sorry for the late reply too I was away for while.

I will explain more precisely the problem I see because reading myself again I admit it's not clear at all:

- If I type in "@h"
- Then I have some mentions displayed matching the "h" text
- Then if I paste "abc" when my cursor is right after "h"
- I get "@h abc" with my cursor after "abc"
- I'm not sure what the problem is here, but I would expect showMentionsListWithString to be called with "h abc" but it's not and the list of suggested mentions remains
- So then I tap one of the suggested mentions, let's say "henry"
=> the full name is inserted before the pasted text so I get "henry  abc" and the cursor is after "henry ", and before " abc"

I hope you see the problem. I can reproduce these steps using your example app so I guess I'm using the lib correctly. Let me know if I can be of any help.

**Comment by szweier** [comment]
@Footjy please try this branch https://github.com/szweier/SZMentionsSwift/pull/88
