### ISSUE TITLE
textView delegates when coming from MentionListner, does not have same behaviour when they are delegated from UITextView

### ISSUE THREAD

**Issue by asim1mehta** [szweier/SZMentionsSwift#87]
Hi

This is just a suggestion.

If `textview` delegating is not deferred and are called in the starting of the functions they will give the same results as actual delegates when coming from `UITextView`.

For example:
When `delegate?.textView?(textView, shouldChangeTextIn: range, replacementText: text)`
is called in MentionListner the string in textView has already been changed.

**Comment by szweier** [comment]
Good point @asim1mehta , I have a large PR I'm working on and I will have this addressed there.
