### ISSUE TITLE
Typing emoji does not trigger textViewDidChange

### ISSUE THREAD

**Issue by ChrisBGriffith** [szweier/SZMentionsSwift#93]
Emojis get caught in the `shouldChangeTextIn` delegate method because their utf16 count is greater than 1. In instances where I'm needing to respond to `textViewDidChange`, it doesn't get called when an emoji is typed.

**Comment by szweier** [comment]
I believe I have a fix for this issue here if you want to take a look https://github.com/szweier/SZMentionsSwift/pull/95
