### ISSUE TITLE
`spaceAfterMention` add space but leaves the cursor (carriage) in its original position

### ISSUE THREAD

**Issue by aleksandrshoshiashvili** [szweier/SZMentionsSwift#96]
The problem in NSRange extension as I could find: 

if `spaceAfterMention = true` then 
  when user tap on mention `func addMention`
    then called `add(createMention, spaceAfterMention: spaceAfterMention, at: currentMentionRange, with: mentionTextAttributes)`
     then called `replace(charactersIn: range, with: mention.mentionName(with: spaceAfterMention))`, but in this place we use the `selectedRange` value obtained without taking into account the parameter `spaceAfterMention` and do not change it and that's why a space was added to the final line, but the cursor remained in the same place.

Well, after changing this
```
internal extension NSRange {
    func adjustLength(for text: String, with spaceAfterMention: Bool) -> NSRange {
        return NSRange(location: location, length: text.utf16.count)
    }
}
```

to this

```
internal extension NSRange {
    func adjustLength(for text: String, with spaceAfterMention: Bool) -> NSRange {
        let lenght = spaceAfterMention ? text.utf16.count + 1 : text.utf16.count
        return NSRange(location: location, length: lenght)
    }
}
```

I fixed the problem, but I'm not sure about the side effects of this fix. Can you check it? Should I submit  a pull request?

**Comment by aleksandrshoshiashvili** [comment]
My fix leads to crash if input emoji after mention :(

**Comment by szweier** [comment]
@aleksandrshoshiashvili can you open a PR with a failing test I can then try to figure out what needs to be done to fix it. Also I don't see a difference to the two code samples you provided in your first comment. What did you change?

**Comment by aleksandrshoshiashvili** [comment]
@szweier Ok, I will open a PR. Sorry, I misspelled in the first comment, now the given pieces of code should be correct

**Comment by aleksandrshoshiashvili** [comment]
@szweier I opened PR #97

**Comment by szweier** [comment]
Thanks for adding that example. I've opened https://github.com/szweier/SZMentionsSwift/pull/98 since I couldn't seem to edit your opened PR. It has your test along with a fix. I'll merge it when tests pass.

**Comment by aleksandrshoshiashvili** [comment]
@szweier thanks!
